In [55]:
from sklearn.datasets import fetch_openml
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.linear_model import SGDClassifier
from sklearn.metrics import confusion_matrix

In [ ]:
mnist = fetch_openml('mnist_784', version=1)

In [ ]:
# X czyli feautures - piksele
# y czyli labele - jaka cyfra powinna byc

# 4. przetestowac na danych na ktorych byl model uczony
#     - || - na danych testowych
#     dwa wyniki dac do listy
    
#     cross_val_score zwraca nd array
    
# 5. 

In [5]:
print((np.array(mnist.data.loc[42]).reshape(28, 28) > 0).astype(int))

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 1 1 1 1 1 1 0 1 1 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 1 1 1 1 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 

In [8]:
type(mnist)

sklearn.utils.Bunch

In [13]:
X, y = mnist["data"], mnist["target"].astype(np.uint8)

In [16]:
y = y.sort_values()

In [17]:
y.index

Int64Index([34999, 56424, 56419, 16705, 56415, 56404, 56397, 56389, 56388,
            56429,
            ...
            13698, 33531, 13695, 13692, 58898, 13687, 42651, 58914, 13678,
            58529],
           dtype='int64', length=70000)

In [18]:
print(y)

34999    0
56424    0
56419    0
16705    0
56415    0
        ..
13687    9
42651    9
58914    9
13678    9
58529    9
Name: class, Length: 70000, dtype: uint8


In [19]:
X = X.reindex(y)

In [24]:
print(X)

       pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  pixel9  \
class                                                                           
0         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
0         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
0         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
0         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
0         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
...       ...     ...     ...     ...     ...     ...     ...     ...     ...   
9         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
9         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
9         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
9         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
9         0.0     0.0     0.

In [26]:
 X_train, X_test = X[:56000], X[56000:]
y_train, y_test = y[:56000], y[56000:]
print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)

(56000, 784) (56000,)
(14000, 784) (14000,)


In [28]:
np.unique(y_train)

array([0, 1, 2, 3, 4, 5, 6, 7], dtype=uint8)

In [29]:
np.unique(y_test)

array([7, 8, 9], dtype=uint8)

In [32]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [34]:
print("y_train: ", np.unique(y_train))

y_train:  [0 1 2 3 4 5 6 7 8 9]


In [35]:
print("y_test: ", np.unique(y_test))

y_test:  [0 1 2 3 4 5 6 7 8 9]


In [39]:
sgd_clf = SGDClassifier()

y_train_0 = (y_train == 0)
y_test_0 = (y_test == 0)

In [40]:
np.unique(y_train_0)

array([False,  True])

In [43]:
sgd_clf.fit(X_train, y_train_0)

SGDClassifier(random_state=42)

In [53]:
train_acc = sgd_clf.score(X_train, y_train_0)
test_acc = sgd_clf.score(X_test, y_test_0)

print("train_acc", train_acc)
print("test_acc", test_acc)
acc_list = list([train_acc, test_acc])
print(acc_list)

# acc_list zapisac jako pickle

train_acc 0.9924821428571429
test_acc 0.991
[0.9924821428571429, 0.991]


In [54]:
y_pred = sgd_clf.predict(X_test)

cv_score = cross_val_score(sgd_clf, X_train, y_train_0, cv=3, scoring="accuracy")
# cs_score zapisac jako pickle

In [56]:
sgd_clf.fit(X_train, y_train)
y_pred = sgd_clf.predict(X_test)

conf_mat = confusion_matrix(y_test, y_pred)
print(conf_mat)

# conf_mat jako pickle

[[1368    0    8    4    2    7    7    1    7    3]
 [   1 1508   13    1    3    7    1    4   28    1]
 [  17    7 1213   40   19    4   35   15   61    5]
 [   8    6   40 1284    8   24    1    7   46   14]
 [   0    4   13    6 1202    0   15    3   11   43]
 [  37    5    3   84   39  871   53    3  115   19]
 [  13    2   17    0   12   11 1302    0    6    0]
 [   7   11   30   19   23    3    1 1249    7  103]
 [  14   30   22   35   22   18   19    7 1210   29]
 [   2    6   16   35   80    6    1   35   12 1231]]
